# No clear secrets in git. Ciphertext only; the in-cluster sealed-secrets
# controller unseals it into Secret ringtoss0-secrets (envFrom). Sealed (strict
# scope) against the dev cluster cert for namespace sdk-apps-dev.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ringtoss0-secrets
  namespace: sdk-apps-dev
spec:
  encryptedData:
    INTERACTIVE_SECRET: AgBL/STlp2JjGeopdUl7SRcopscENc/hm76EQeEWiyQDTymTErc7SoO/015bNkZ5omyq8zWBF2NZBGr8qA6Saj4ZDqDQn/+LzVDQQEYCWmjXuLgb0GyExihenE9jeHnPIhzkI1+cvODU+Lzq7KHnsE6l42WIPHsv9v6KgJTh0rlodcX2gHr7/CCBUmj55QxSEtAwVLfwXOBsJY6G7GRXSklNkF7aWbKv4hwVobpFqBGC7C8KesgZU/kvEq/lVZQs1bbUFjSdQX858HHe6DD+K7qn8bJ9z2Y84T5n19a+k+/PMUx0HgJMWSKNcHPtBa6JfAf2TbCVqYpjL6xabrC+c3Is1D0fGgGxHo2yh7A97Vn1BfeujOXwfsq98wMyS90PwaBpE3VnxRlNa3pG/TrqjlH0vSntGq4KGZyVF8nh3Gj/hOR28Tk4wsDOHA0eB7qwvrdK6jARYkRTp3mBZTaOvXg/o+ibFFxbP1v0U6K5UHLUE/6pImfvFnri4dwWfQi8eS8gQszYziZ8oF0Gbz/aBXsGhYKUV7Zsn0NyzJNDeg2/+3FIFqp3P4Aq99nAnzTxkfCLTF/GB/qlwNyuGR0QxxAaao0wRT6i4TXvnh00wp3hkKCoVp7LV8T9jAL178kagkiVClkil3SD0rVY/xfF3UifdXqEQo8wi2V5YkYhX7qQ9bgtC8lR5/yDocjKE/EgUOT6MA1YwAY00LGu+eCYM4Q4XI/hGYODaiqJ92rRcHiFiSwqVISu6MV4sZ3Va0Pou28=
  template:
    metadata:
      name: ringtoss0-secrets
      namespace: sdk-apps-dev
    type: Opaque
